export enum TokenCode {
  BLUR = 'BLUR',
  bNEO = 'bNEO',
  BUSD = 'BUSD',
  USD = 'USD',
  ETH = 'ETH',
  GMX = 'GMX',
  STEVMOS = 'stEVMOS',
  LUNA = 'LUNA',
  RATOM = 'rATOM',
  STRD = 'STRD',
  EVMOS = 'EVMOS',
  IBCX = 'IBCX',
  IRIS = 'IRIS',
  ampLUNA = 'ampLUNA',
  KUJI = 'KUJI',
  STOSMO = 'stOSMO',
  axlUSDC = 'axlUSDC',
  ATOM = 'ATOM',
  STATOM = 'stATOM',
  OSMO = 'OSMO',
  rSWTH = 'rSWTH',
  STLUNA = 'stLUNA',
  LSI = 'LSI',
  OKB = 'OKB',
  OKT = 'OKT',
  SWTH = 'SWTH',
  USC = 'USC',
  USDC = 'USDC',
  WBTC = 'WBTC',
  wstETH = 'wstETH',
  YieldUSD = 'YieldUSD',
  ZIL = 'ZIL'
}

